### ISSUE TITLE
migration not running

### ISSUE THREAD

**Issue by chmich** [eckucukoglu/redmine-reminder-emails#27]
dear eckucukoglu,

why is migration not running?

previous, i installed your plugin, for testing, on redmine 4.0.4, in env=development, it ran without problems.
than, on the live-system (production):

```
$ cd /path/to/redmine/plugins
$ git clone https://github.com/eckucukoglu/redmine-reminder-emails reminderemails
$ RAILS_ENV=production rake redmine:plugins:migrate

... and then: 


Migrating reminderemails (Reminder E-mails plugin)...
-- [](4.2)
-- [](4.2)
rake aborted!
NoMethodError: undefined method `[]' for #<ActiveRecord::Migration:0x0000000002263b38>
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:664:in `block in method_missing'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `block in say_with_time'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `say_with_time'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:654:in `method_missing'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:416:in `method_missing'
/usr/share/redmine/plugins/reminderemails/db/migrate/001_create_reminder_entries.rb:1:in `<top (required)>'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:777:in `load_migration'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:773:in `migration'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `disable_ddl_transaction'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:1051:in `use_transaction?'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:961:in `rescue in block in migrate'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:958:in `block in migrate'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/usr/share/redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/usr/share/redmine/lib/redmine/plugin.rb:453:in `migrate'
/usr/share/redmine/lib/redmine/plugin.rb:467:in `block in migrate'
/usr/share/redmine/lib/redmine/plugin.rb:466:in `each'
/usr/share/redmine/lib/redmine/plugin.rb:466:in `migrate'
/usr/share/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'

Caused by:
NoMethodError: undefined method `[]' for #<ActiveRecord::Migration:0x0000000002263b38>
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:664:in `block in method_missing'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `block in say_with_time'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `say_with_time'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:654:in `method_missing'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:416:in `method_missing'
/usr/share/redmine/plugins/reminderemails/db/migrate/001_create_reminder_entries.rb:1:in `<top (required)>'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:777:in `load_migration'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:773:in `migration'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `disable_ddl_transaction'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:1051:in `use_transaction?'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:1043:in `ddl_transaction'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:959:in `block in migrate'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/var/lib/gems/2.5.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/usr/share/redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/usr/share/redmine/lib/redmine/plugin.rb:453:in `migrate'
/usr/share/redmine/lib/redmine/plugin.rb:467:in `block in migrate'
/usr/share/redmine/lib/redmine/plugin.rb:466:in `each'
/usr/share/redmine/lib/redmine/plugin.rb:466:in `migrate'
/usr/share/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
sasadmin@soweb02:/usr/share/redmine/plugins$

```

**Comment by eckucukoglu** [comment]
hi chmich,

i am sorry to hear that; unfortunately i don't develop redmine anymore.
I wrote this plugin for version3. thanks to open community, one of the guys here helped us to upgrade for version 4. so, you may try to check that pull request to see if something wrong there. however if you have already tried in test environment with up-to-date version; then I really don't know. 

anyone here to help are welcomed.
